# Generated by Django 5.2.4 on 2025-08-09 09:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readinglists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='readinglist',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_reading_list'),
        ),
    ]
