# Generated by Django 5.2.4 on 2025-08-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_books_options_books_unique_book_per_user'),
        ('readinglists', '0002_readinglist_unique_reading_list'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='readinglistbook',
            constraint=models.UniqueConstraint(fields=('reading_list', 'book'), name='unique_reading_list_book'),
        ),
        migrations.AddConstraint(
            model_name='readinglistbook',
            constraint=models.UniqueConstraint(fields=('reading_list', 'order'), name='unique_order_per_list'),
        ),
    ]
