# Generated by Django 5.2.4 on 2025-08-11 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readinglists', '0003_readinglistbook_unique_reading_list_book_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readinglistbook',
            options={'ordering': ['order']},
        ),
    ]
