# Generated by Django 5.2.4 on 2025-08-11 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readinglists', '0004_alter_readinglistbook_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='readinglistbook',
            name='unique_order_per_list',
        ),
    ]
