# Generated by Django 5.2.4 on 2025-08-06 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=110)),
                ('genre', models.CharField(max_length=100)),
                ('cover_image', models.ImageField(null=True, upload_to='books/image')),
                ('description', models.TextField()),
                ('publication_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='books.author')),
                ('upload_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
