# Generated by Django 5.2.4 on 2025-08-07 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='author',
        ),
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.ManyToManyField(related_name='author', to='books.author'),
        ),
    ]
