# Generated by Django 5.2.4 on 2025-08-09 06:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_books_upload_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ['-publication_date']},
        ),
        migrations.AddConstraint(
            model_name='books',
            constraint=models.UniqueConstraint(fields=('upload_by', 'title'), name='unique_book_per_user'),
        ),
    ]
